USE [GD2C2023]
GO

-- Inicio Configurar reglas de nombre de objetos
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET CONCAT_NULL_YIELDS_NULL ON
GO
-- Fin Configurar reglas de nombre de objetos

-- Inicio DROP FKs
IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_DETALLE_IMPORTE_ALQ_ALQUILER_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DETALLE_IMPORTE_ALQ
    DROP CONSTRAINT FK_DETALLE_IMPORTE_ALQ_ALQUILER_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_PAGO_ALQUILER_ALQUILER_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER
    DROP CONSTRAINT FK_PAGO_ALQUILER_ALQUILER_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_PAGO_ALQUILER_MEDIO_PAGO_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER
    DROP CONSTRAINT FK_PAGO_ALQUILER_MEDIO_PAGO_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_PAGO_VENTA_TIPO_MONEDA_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
    DROP CONSTRAINT FK_PAGO_VENTA_TIPO_MONEDA_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_PAGO_VENTA_MEDIO_PAGO_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
    DROP CONSTRAINT FK_PAGO_VENTA_MEDIO_PAGO_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_PAGO_VENTA_VENTA_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
    DROP CONSTRAINT FK_PAGO_VENTA_VENTA_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_INMUEBLE_ORIENTACION_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    DROP CONSTRAINT FK_INMUEBLE_ORIENTACION_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_INMUEBLE_DISPOSICION_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    DROP CONSTRAINT FK_INMUEBLE_DISPOSICION_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_INMUEBLE_TIPO_INMUEBLE_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    DROP CONSTRAINT FK_INMUEBLE_TIPO_INMUEBLE_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_INMUEBLE_AMBIENTES_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    DROP CONSTRAINT FK_INMUEBLE_AMBIENTES_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_INMUEBLE_ESTADO_INMUEBLE_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    DROP CONSTRAINT FK_INMUEBLE_ESTADO_INMUEBLE_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_INMUEBLE_BARRIO_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    DROP CONSTRAINT FK_INMUEBLE_BARRIO_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_CARACTERISTICA_X_INMUEBLE_CODIGO_INMUEBLE',
             'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE
    DROP CONSTRAINT FK_CARACTERISTICA_X_INMUEBLE_CODIGO_INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_CARACTERISTICA_X_INMUEBLE_CARACTERISTICA_INMUEBLE_ID',
             'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE
    DROP CONSTRAINT FK_CARACTERISTICA_X_INMUEBLE_CARACTERISTICA_INMUEBLE_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_ANUNCIO_AGENTE_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
    DROP CONSTRAINT FK_ANUNCIO_AGENTE_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_ANUNCIO_TIPO_PERIODO_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
    DROP CONSTRAINT FK_ANUNCIO_TIPO_PERIODO_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_ANUNCIO_TIPO_OPERACION_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
    DROP CONSTRAINT FK_ANUNCIO_TIPO_OPERACION_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_ANUNCIO_ESTADO_ANUNCIO_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
    DROP CONSTRAINT FK_ANUNCIO_ESTADO_ANUNCIO_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_ANUNCIO_INMUEBLE_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
    DROP CONSTRAINT FK_ANUNCIO_INMUEBLE_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_ANUNCIO_TIPO_MONEDA_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
    DROP CONSTRAINT FK_ANUNCIO_TIPO_MONEDA_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_AGENTE_SUCURSAL_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AGENTE
    DROP CONSTRAINT FK_AGENTE_SUCURSAL_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_AGENTE_PERSONA_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AGENTE
    DROP CONSTRAINT FK_AGENTE_PERSONA_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_SUCURSAL_LOCALIDAD_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.SUCURSAL
    DROP CONSTRAINT FK_SUCURSAL_LOCALIDAD_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_LOCALIDAD_PROVINCIA_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.LOCALIDAD
    DROP CONSTRAINT FK_LOCALIDAD_PROVINCIA_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_BARRIO_LOCALIDAD_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO
    DROP CONSTRAINT FK_BARRIO_LOCALIDAD_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_VENTA_TIPO_MONEDA_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.VENTA
    DROP CONSTRAINT FK_VENTA_TIPO_MONEDA_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_VENTA_ANUNCIO_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.VENTA
    DROP CONSTRAINT FK_VENTA_ANUNCIO_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_COMPRADOR_PERSONA_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.COMPRADOR
    DROP CONSTRAINT FK_COMPRADOR_PERSONA_ID
GO
-- Fin DROP FKs

-- Inicio DROP Unique Keys
IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.UQ_PROPIETARIO', 'UQ') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROPIETARIO
    DROP CONSTRAINT UQ_PROPIETARIO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.UQ_INQUILINO', 'UQ') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INQUILINO
    DROP CONSTRAINT UQ_INQUILINO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.UQ_COMPRADOR', 'UQ') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.COMPRADOR
    DROP CONSTRAINT UQ_COMPRADOR
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.UQ_ALQUILER', 'UQ') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ALQUILER
    DROP CONSTRAINT UQ_ALQUILER
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.UQ_PROVINCIA_X_LOCALIDAD', 'UQ') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA_X_LOCALIDAD
    DROP CONSTRAINT UQ_PROVINCIA_X_LOCALIDAD
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.UQ_BARRIO_X_LOCALIDAD', 'UQ') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO_X_LOCALIDAD
    DROP CONSTRAINT UQ_BARRIO_X_LOCALIDAD
GO
-- Fin DROP Unique Keys

-- Inicio DROP tablas
IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DETALLE_IMPORTE_ALQ', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DETALLE_IMPORTE_ALQ
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ALQUILER', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ALQUILER
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MEDIO_PAGO', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MEDIO_PAGO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_MONEDA', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_MONEDA
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DISPOSICION', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DISPOSICION
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ORIENTACION', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ORIENTACION
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_INMUEBLE', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AMBIENTES', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AMBIENTES
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_INMUEBLE', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_INMUEBLE', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_PERIODO', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_PERIODO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_OPERACION', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_OPERACION
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ANUNCIO', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ANUNCIO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AGENTE', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AGENTE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.SUCURSAL', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.SUCURSAL
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.LOCALIDAD', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.LOCALIDAD
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.VENTA', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.VENTA
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ALQUILER', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ALQUILER
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.COMPRADOR', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.COMPRADOR
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INQUILINO', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INQUILINO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PERSONA', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PERSONA
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROPIETARIO', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROPIETARIO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA_X_LOCALIDAD', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA_X_LOCALIDAD
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO_X_LOCALIDAD', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO_X_LOCALIDAD
GO
-- Fin DROP tablas

-- Inicio DROP Funciones

-- Fin DROP Funciones

-- Inicio DROP Procedimientos
IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PROPIETARIO') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PROPIETARIO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_INQUILINO') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_INQUILINO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_COMPRADOR') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_COMPRADOR
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_DISPOSICION') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_DISPOSICION
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_AMBIENTES') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_AMBIENTES
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ESTADO_INMUEBLE') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ESTADO_INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_INMUEBLE') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ORIENTACION') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ORIENTACION
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PROVINCIA') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PROVINCIA
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_LOCALIDAD') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_LOCALIDAD
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_BARRIO') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_BARRIO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_SUCURSAL') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_SUCURSAL
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PERSONA') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PERSONA
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_AMBIENTES') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_AMBIENTES
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ESTADO_ALQUILER') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ESTADO_ALQUILER
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ESTADO_ANUNCIO') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ESTADO_ANUNCIO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_MEDIO_PAGO') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_MEDIO_PAGO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_MONEDA') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_MONEDA
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_OPERACION') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_OPERACION
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_PERIODO') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_PERIODO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_AGENTE') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_AGENTE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_INMUEBLE') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ANUNCIO') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ANUNCIO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PROVINCIA_X_LOCALIDAD') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PROVINCIA_X_LOCALIDAD
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_BARRIO_X_LOCALIDAD') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_BARRIO_X_LOCALIDAD
GO
-- Fin DROP Procedimientos

-- Inicio crear schema de la aplicación
IF EXISTS (SELECT SCHEMA_NAME
           FROM INFORMATION_SCHEMA.SCHEMATA
           WHERE SCHEMA_NAME = 'LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO')
    DROP SCHEMA LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO
GO

CREATE SCHEMA LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO
GO
-- Fin crear schema de la aplicación

-- Inicio crear tablas
CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DETALLE_IMPORTE_ALQ
(
    codigo             NUMERIC(19, 0) PRIMARY KEY,
    alquiler_id        NUMERIC(19, 0) NOT NULL,
    nro_periodo_inicio NUMERIC(19, 2) NULL,
    nro_periodo_fin    NUMERIC(19, 2) NULL,
    precio             NUMERIC(19, 2) NULL,
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER
(
    codigo            NUMERIC(19, 0) PRIMARY KEY,
    alquiler_id       NUMERIC(19, 0) NOT NULL,
    fecha_pago        DATETIME       NULL,
    nro_periodo_pago  NUMERIC(19, 0) NULL,
    descripcion       NVARCHAR(100)  NULL,
    fecha_inicio_pago DATETIME       NULL,
    fecha_fin_pago    DATETIME       NULL,
    importe           NUMERIC(19, 0) NULL,
    medio_pago_id     NVARCHAR(100)  NOT NULL,
    fecha_vencimiento DATETIME       NULL,
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
(
    codigo         NUMERIC(19, 0) PRIMARY KEY,
    importe        NUMERIC(19, 2) NULL,
    tipo_moneda_id NVARCHAR(100)  NOT NULL,
    cotizacion     NUMERIC(19, 2) NULL,
    medio_pago_id  NVARCHAR(100)  NOT NULL,
    venta_id       NUMERIC(19, 0) NOT NULL,
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ALQUILER
(
    --id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MEDIO_PAGO
(
    --id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_MONEDA
(
    --id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
(
    codigo             NUMERIC(19, 0) PRIMARY KEY,
    tipo_inmueble_id   NVARCHAR(100),
    descripcion        NVARCHAR(100),
    nombre             NVARCHAR(100),
    propietario_id     NUMERIC(19, 0),
    barrio_id          NVARCHAR(100),
    ambientes_id       NVARCHAR(100),
    superficie_total   NUMERIC(19, 0),
    disposicion_id     NVARCHAR(100),
    orientacion_id     NVARCHAR(100),
    estado_inmueble_id NVARCHAR(100),
    antiguedad         NUMERIC(19, 0),
    expensas           NUMERIC(19, 0)
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ORIENTACION
(
    --id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY,
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DISPOSICION
(
    --id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_INMUEBLE
(
    -- id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AMBIENTES
(
    --id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_INMUEBLE
(
    --id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_INMUEBLE
(
    --id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY,
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE
(
    codigo_inmueble            NUMERIC(19, 0),
    caracteristica_inmueble_id NVARCHAR(100),
    PRIMARY KEY (codigo_inmueble, caracteristica_inmueble_id),
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_PERIODO
(
    --id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY,
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_OPERACION
(
    --id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY,
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ANUNCIO
(
    -- id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY,
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA
(
    -- id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY,
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.LOCALIDAD
(
    -- id           NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA_X_LOCALIDAD
(
    provincia_id NVARCHAR(100),
    localidad_id NVARCHAR(100),
    PRIMARY KEY (provincia_id, localidad_id),
)

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO
(
    -- id           NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    id NVARCHAR(100) PRIMARY KEY
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO_X_LOCALIDAD
(
    barrio_id    NVARCHAR(100),
    localidad_id NVARCHAR(100),
    PRIMARY KEY (barrio_id, localidad_id),
)

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.SUCURSAL
(
    codigo       NUMERIC(19, 0) PRIMARY KEY,
    direccion    NVARCHAR(100),
    localidad_id NVARCHAR(100),
    nombre       NVARCHAR(100),
    telefono     NVARCHAR(100),
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AGENTE
(
    id          NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    persona_id  NUMERIC(19, 0),
    sucursal_id NUMERIC(19, 0),
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
(
    codigo                    NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    agente_id                 NUMERIC(19, 0),
    costo_publicacion_anuncio NUMERIC(19, 2),
    estado_anuncio_id         NVARCHAR(100),
    fecha_finalizacion        DATETIME,
    fecha_publicacion         DATETIME,
    inmueble_id               NUMERIC(19, 0),
    precio_publicado          NUMERIC(19, 2),
    tipo_moneda_id            NVARCHAR(100),
    tipo_operacion_id         NVARCHAR(100),
    tipo_periodo_id           NVARCHAR(100),
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PERSONA
(
    id             NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    apellido       NVARCHAR(100),
    dni            NUMERIC(19, 0),
    fecha_nac      DATETIME,
    fecha_registro DATETIME,
    mail           NVARCHAR(100),
    nombre         NVARCHAR(100),
    telefono       NUMERIC(19, 0),
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.VENTA
(
    codigo         NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    comprador_id   NUMERIC(19, 0),
    fecha_venta    DATETIME,
    precio_venta   NUMERIC(19, 2),
    tipo_moneda_id NVARCHAR(100),
    comision       NUMERIC(19, 2),
    anuncio_id     NUMERIC(19, 0),
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ALQUILER
(
    codigo                NUMERIC(19, 0) IDENTITY (1, 1) PRIMARY KEY,
    inquilino_id          NUMERIC(19, 0),
    fecha_inicio_alquiler DATETIME,
    fecha_fin_alquiler    DATETIME,
    cant_periodos         NUMERIC(19, 0),
    deposito              NUMERIC(19, 2),
    comision              NUMERIC(19, 2),
    gastos_averiguaciones NUMERIC(19, 2),
    estado_id             NUMERIC(19, 0),
    anuncio_id            NUMERIC(19, 0),
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.COMPRADOR
(
    persona_id   NUMERIC(19, 0),
    codigo_venta NUMERIC(19, 0),
    PRIMARY KEY (persona_id, codigo_venta),
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INQUILINO
(
    persona_id      NUMERIC(19, 0),
    codigo_alquiler NUMERIC(19, 0),
    PRIMARY KEY (persona_id, codigo_alquiler),
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROPIETARIO
(
    persona_id  NUMERIC(19, 0),
    inmueble_id NUMERIC(19, 0),
    PRIMARY KEY (persona_id, inmueble_id),
)
GO
-- Fin crear tablas

-- Inicio crear FKs
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DETALLE_IMPORTE_ALQ
    ADD CONSTRAINT FK_DETALLE_IMPORTE_ALQ_ALQUILER_ID FOREIGN KEY (alquiler_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ALQUILER (codigo)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER
    ADD CONSTRAINT FK_PAGO_ALQUILER_ALQUILER_ID FOREIGN KEY (alquiler_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ALQUILER (codigo)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER
    ADD CONSTRAINT FK_PAGO_ALQUILER_MEDIO_PAGO_ID FOREIGN KEY (MEDIO_PAGO_ID) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MEDIO_PAGO (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
    ADD CONSTRAINT FK_PAGO_VENTA_TIPO_MONEDA_ID FOREIGN KEY (tipo_moneda_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_MONEDA (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
    ADD CONSTRAINT FK_PAGO_VENTA_MEDIO_PAGO_ID FOREIGN KEY (medio_pago_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MEDIO_PAGO (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
    ADD CONSTRAINT FK_PAGO_VENTA_VENTA_ID FOREIGN KEY (venta_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.VENTA (codigo)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    ADD CONSTRAINT FK_INMUEBLE_ORIENTACION_ID FOREIGN KEY (orientacion_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ORIENTACION (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    ADD CONSTRAINT FK_INMUEBLE_DISPOSICION_ID FOREIGN KEY (disposicion_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DISPOSICION (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    ADD CONSTRAINT FK_INMUEBLE_TIPO_INMUEBLE_ID FOREIGN KEY (tipo_inmueble_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_INMUEBLE (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    ADD CONSTRAINT FK_INMUEBLE_AMBIENTES_ID FOREIGN KEY (ambientes_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AMBIENTES (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    ADD CONSTRAINT FK_INMUEBLE_ESTADO_INMUEBLE_ID FOREIGN KEY (estado_inmueble_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_INMUEBLE (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    ADD CONSTRAINT FK_INMUEBLE_BARRIO_ID FOREIGN KEY (barrio_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE
    ADD CONSTRAINT FK_CARACTERISTICA_X_INMUEBLE_CODIGO_INMUEBLE FOREIGN KEY (codigo_inmueble) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE (codigo)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE
    ADD CONSTRAINT FK_CARACTERISTICA_X_INMUEBLE_CARACTERISTICA_INMUEBLE_ID FOREIGN KEY (caracteristica_inmueble_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_INMUEBLE (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
    ADD CONSTRAINT FK_ANUNCIO_AGENTE_ID FOREIGN KEY (agente_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AGENTE (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
    ADD CONSTRAINT FK_ANUNCIO_TIPO_PERIODO_ID FOREIGN KEY (tipo_periodo_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_PERIODO (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
    ADD CONSTRAINT FK_ANUNCIO_TIPO_OPERACION_ID FOREIGN KEY (tipo_operacion_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_OPERACION (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
    ADD CONSTRAINT FK_ANUNCIO_ESTADO_ANUNCIO_ID FOREIGN KEY (estado_anuncio_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ANUNCIO (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
    ADD CONSTRAINT FK_ANUNCIO_INMUEBLE_ID FOREIGN KEY (inmueble_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE (codigo)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO
    ADD CONSTRAINT FK_ANUNCIO_TIPO_MONEDA_ID FOREIGN KEY (tipo_moneda_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_MONEDA (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AGENTE
    ADD CONSTRAINT FK_AGENTE_SUCURSAL_ID FOREIGN KEY (sucursal_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.SUCURSAL (codigo)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AGENTE
    ADD CONSTRAINT FK_AGENTE_PERSONA_ID FOREIGN KEY (persona_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PERSONA (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.SUCURSAL
    ADD CONSTRAINT FK_SUCURSAL_LOCALIDAD_ID FOREIGN KEY (localidad_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.LOCALIDAD (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.VENTA
    ADD CONSTRAINT FK_VENTA_TIPO_MONEDA_ID FOREIGN KEY (tipo_moneda_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_MONEDA (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.VENTA
    ADD CONSTRAINT FK_VENTA_ANUNCIO_ID FOREIGN KEY (anuncio_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO (codigo)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.COMPRADOR
    ADD CONSTRAINT FK_COMPRADOR_PERSONA_ID FOREIGN KEY (persona_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PERSONA (id)
GO
-- Fin crear FKs

-- Inicio crear Unique Keys
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROPIETARIO
    ADD CONSTRAINT UQ_PROPIETARIO UNIQUE (persona_id, inmueble_id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.COMPRADOR
    ADD CONSTRAINT UQ_COMPRADOR UNIQUE (persona_id, codigo_venta)

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INQUILINO
    ADD CONSTRAINT UQ_INQUILINO UNIQUE (persona_id, codigo_alquiler)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ALQUILER
    ADD CONSTRAINT UQ_ALQUILER UNIQUE (codigo, anuncio_id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA_X_LOCALIDAD
    ADD CONSTRAINT UQ_PROVINCIA_X_LOCALIDAD UNIQUE (provincia_id, localidad_id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO_X_LOCALIDAD
    ADD CONSTRAINT UQ_BARRIO_X_LOCALIDAD UNIQUE (barrio_id, localidad_id)
GO
-- Fin crear Unique Keys

-- Inicio crear Funciones

-- Fin crear Funciones

-- Inicio crear Procedimientos

/*

--ALQUILER
CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ALQUILER
AS
BEGIN

  INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ALQUILER(codigo, inquilino_id, fecha_inicio_alquiler, fecha_fin_alquiler, cant_periodos, deposito, comision, gastos_averiguaciones, estado_id, anuncio_id)
  SELECT DISTINCT ALQUILER_CODIGO, i.persona_id, ALQUILER_FECHA_INICIO, ALQUILER_FECHA_FIN, ALQUILER_CANT_PERIODOS, ALQUILER_DEPOSITO, ALQUILER_COMISION, ALQUILER_GASTOS_AVERIGUA, ea.id, a.codigo
  FROM gd_esquema.Maestra m
  JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INQUILINO i ON i.persona_id =
  JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ALQUILER ea ON ea.id = m.ALQUILER_ESTADO
  JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO a ON a.codigo = m.ANUNCIO_CODIGO
END
GO
*/

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_DISPOSICION
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DISPOSICION(id)
    SELECT DISTINCT INMUEBLE_DISPOSICION
    FROM GD_ESQUEMA.MAESTRA
    /* Filtrar las disposiciones cuyos valores sean NULL, debido a que el caso en el que respecta dicho valor NULL
       se trata de la definición de otra entidad que no era INMUEBLE_DISPOSICION */
    WHERE INMUEBLE_DISPOSICION IS NOT NULL
    ORDER BY 1
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_AMBIENTES
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AMBIENTES(id)
    SELECT DISTINCT INMUEBLE_CANT_AMBIENTES
    FROM GD_ESQUEMA.MAESTRA
    WHERE INMUEBLE_CANT_AMBIENTES IS NOT NULL
    ORDER BY 1
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ESTADO_INMUEBLE
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_INMUEBLE(id)
    SELECT DISTINCT INMUEBLE_ESTADO
    FROM GD_ESQUEMA.MAESTRA
    WHERE INMUEBLE_ESTADO IS NOT NULL
    ORDER BY 1
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_INMUEBLE
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_INMUEBLE(id)
    SELECT DISTINCT INMUEBLE_TIPO_INMUEBLE
    FROM GD_ESQUEMA.MAESTRA
    WHERE INMUEBLE_TIPO_INMUEBLE IS NOT NULL
    ORDER BY 1
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ORIENTACION
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ORIENTACION(id)
    SELECT DISTINCT INMUEBLE_ORIENTACION
    FROM GD_ESQUEMA.MAESTRA
    WHERE INMUEBLE_ORIENTACION IS NOT NULL
    ORDER BY 1
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PROVINCIA
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA(id)
    SELECT DISTINCT GD_ESQUEMA.MAESTRA.INMUEBLE_PROVINCIA
    FROM GD_ESQUEMA.MAESTRA
    WHERE INMUEBLE_PROVINCIA IS NOT NULL
    ORDER BY 1
END
GO

/*
SELECT GD_ESQUEMA.MAESTRA.INMUEBLE_LOCALIDAD, p.id
    FROM GD_ESQUEMA.MAESTRA
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA p
                  ON p.id = GD_ESQUEMA.MAESTRA.INMUEBLE_PROVINCIA
    UNION
    SELECT GD_ESQUEMA.MAESTRA.SUCURSAL_LOCALIDAD, p.id
    FROM GD_ESQUEMA.MAESTRA
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA p
                  ON p.id = GD_ESQUEMA.MAESTRA.SUCURSAL_PROVINCIA
    GROUP BY GD_ESQUEMA.MAESTRA.SUCURSAL_LOCALIDAD, p.id
    ORDER BY 1
*/

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_LOCALIDAD
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.LOCALIDAD(id)
    SELECT DISTINCT GD_ESQUEMA.MAESTRA.INMUEBLE_LOCALIDAD
    FROM GD_ESQUEMA.MAESTRA
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA p
                  ON p.id = GD_ESQUEMA.MAESTRA.INMUEBLE_PROVINCIA
    UNION
    SELECT DISTINCT GD_ESQUEMA.MAESTRA.SUCURSAL_LOCALIDAD
    FROM GD_ESQUEMA.MAESTRA
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA p
                  ON p.id = GD_ESQUEMA.MAESTRA.SUCURSAL_PROVINCIA
    WHERE INMUEBLE_LOCALIDAD IS NOT NULL
    ORDER BY 1
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_BARRIO
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO(id)
    SELECT DISTINCT GD_ESQUEMA.MAESTRA.INMUEBLE_BARRIO
    FROM GD_ESQUEMA.MAESTRA
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.LOCALIDAD l
                  ON l.id = GD_ESQUEMA.MAESTRA.INMUEBLE_LOCALIDAD
    WHERE INMUEBLE_BARRIO IS NOT NULL
    GROUP BY GD_ESQUEMA.MAESTRA.INMUEBLE_BARRIO
    ORDER BY 1
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_SUCURSAL
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.SUCURSAL(codigo, direccion, localidad_id, nombre, telefono)
    SELECT DISTINCT SUCURSAL_CODIGO, SUCURSAL_DIRECCION, l.id, SUCURSAL_NOMBRE, SUCURSAL_TELEFONO
    FROM GD_ESQUEMA.MAESTRA
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.LOCALIDAD l
                  ON l.id = GD_ESQUEMA.MAESTRA.SUCURSAL_LOCALIDAD
    WHERE SUCURSAL_DIRECCION IS NOT NULL
    ORDER BY 1
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PERSONA
AS
BEGIN
    -- No se realiza el DISTINCT por cada SELECT, ya que el UNION se encarga de eliminar los duplicados
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PERSONA(dni, apellido, fecha_nac, fecha_registro, mail, nombre, telefono)
    SELECT AGENTE_DNI,
           AGENTE_APELLIDO,
           AGENTE_FECHA_NAC,
           AGENTE_FECHA_REGISTRO,
           AGENTE_MAIL,
           AGENTE_NOMBRE,
           AGENTE_TELEFONO
    FROM gd_esquema.Maestra
    WHERE AGENTE_DNI IS NOT NULL
    UNION
    SELECT COMPRADOR_DNI,
           COMPRADOR_APELLIDO,
           COMPRADOR_FECHA_NAC,
           COMPRADOR_FECHA_REGISTRO,
           COMPRADOR_MAIL,
           COMPRADOR_NOMBRE,
           COMPRADOR_TELEFONO
    FROM gd_esquema.Maestra
    WHERE COMPRADOR_DNI IS NOT NULL
    UNION
    SELECT INQUILINO_DNI,
           INQUILINO_APELLIDO,
           INQUILINO_FECHA_NAC,
           INQUILINO_FECHA_REGISTRO,
           INQUILINO_MAIL,
           INQUILINO_NOMBRE,
           INQUILINO_TELEFONO
    FROM gd_esquema.Maestra
    WHERE INQUILINO_DNI IS NOT NULL
    UNION
    SELECT PROPIETARIO_DNI,
           PROPIETARIO_APELLIDO,
           PROPIETARIO_FECHA_NAC,
           PROPIETARIO_FECHA_REGISTRO,
           PROPIETARIO_MAIL,
           PROPIETARIO_NOMBRE,
           PROPIETARIO_TELEFONO
    FROM gd_esquema.Maestra
    WHERE PROPIETARIO_DNI IS NOT NULL
    ORDER BY 1
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_PERIODO
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_PERIODO(id)
    -- En caso de que ANUNCIO_TIPO_PERIODO sea 0, indica que fue vendido o que caducó el anuncio
    SELECT DISTINCT ANUNCIO_TIPO_PERIODO
    FROM gd_esquema.Maestra m
    ORDER BY 1
END
GO

--ESTADO_ANUNCIO
CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ESTADO_ANUNCIO
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ANUNCIO(id)
    SELECT DISTINCT ANUNCIO_ESTADO
    FROM gd_esquema.Maestra m
    ORDER BY 1
END
GO

--TIPO_OPERACION
CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_OPERACION
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_OPERACION(id)
    SELECT DISTINCT ANUNCIO_TIPO_OPERACION
    FROM gd_esquema.Maestra m
    ORDER BY 1
END
GO

--ESTADO_ALQUILER
CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ESTADO_ALQUILER
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ALQUILER(id)
    SELECT DISTINCT ALQUILER_ESTADO
    FROM gd_esquema.Maestra m
    WHERE ALQUILER_ESTADO IS NOT NULL
    ORDER BY 1
    --Decidimos sacar los valores null porque no hay ningun alquiler con estado_alquiler en null
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_MEDIO_PAGO
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MEDIO_PAGO(id)
    SELECT DISTINCT PAGO_VENTA_MEDIO_PAGO
    FROM gd_esquema.Maestra m
    WHERE PAGO_VENTA_MEDIO_PAGO IS NOT NULL
    ORDER BY 1
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_MONEDA
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_MONEDA(id)
    SELECT DISTINCT PAGO_VENTA_MONEDA
    FROM gd_esquema.Maestra m
    WHERE PAGO_VENTA_MONEDA IS NOT NULL
    ORDER BY 1
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_COMPRADOR
AS
BEGIN
    -- Depende de MIGRAR_VENTA
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.COMPRADOR(persona_id, codigo_venta)
    SELECT DISTINCT p.id, m.VENTA_CODIGO
    FROM gd_esquema.Maestra m
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PERSONA p ON p.mail = m.COMPRADOR_MAIL
    ORDER BY 1
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_INQUILINO
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INQUILINO(persona_id, codigo_alquiler)
    SELECT DISTINCT p.id, m.ALQUILER_CODIGO
    FROM gd_esquema.Maestra m
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PERSONA p ON p.mail = m.INQUILINO_MAIL
    GROUP BY p.id, m.ALQUILER_CODIGO
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PROPIETARIO
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROPIETARIO(persona_id, inmueble_id)
    SELECT DISTINCT p.id, m.INMUEBLE_CODIGO
    FROM gd_esquema.Maestra m
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PERSONA p ON p.mail = m.PROPIETARIO_MAIL
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_AGENTE
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AGENTE(persona_id, sucursal_id)
    SELECT DISTINCT p.id, s.codigo
    FROM gd_esquema.Maestra m
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PERSONA p ON p.mail = m.AGENTE_MAIL
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.SUCURSAL s ON s.codigo = m.SUCURSAL_CODIGO
END
GO

--VENTA (falta mapear id de persona y de tipo moneda)
--CADA PROPIEDAD SE OFRECE TANTO EN PESOS COMO EN DOLARES Y POR LO TANTO HAY MAS "VENTAS"
/*
CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_VENTA
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.VENTA(codigo, comprador_id, fecha_venta, precio_venta,
                                                                    tipo_moneda_id, comision, anuncio_id)
    SELECT DISTINCT VENTA_CODIGO, c.persona_id, VENTA_FECHA, VENTA_PRECIO_VENTA, tm.id, VENTA_COMISION, a.codigo
    FROM gd_esquema.Maestra m
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.COMPRADOR c ON c.persona_id =
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_MONEDA tm ON tm.id = m.VENTA_MONEDA
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO a ON a.codigo = m.ANUNCIO_CODIGO
END
GO
*/

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_INMUEBLE
AS
BEGIN
    -- (1): empleo de mail para unicidad en la identificación del propietario, propietario no posee Id en tabla maestra
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE(codigo, tipo_inmueble_id, descripcion, nombre,
                                                                       propietario_id, barrio_id,
                                                                       ambientes_id, superficie_total, disposicion_id,
                                                                       orientacion_id, estado_inmueble_id, antiguedad,
                                                                       expensas)
    SELECT DISTINCT m.INMUEBLE_CODIGO,
                    TipoInmueble.id,
                    m.INMUEBLE_DESCRIPCION,
                    m.INMUEBLE_NOMBRE,
                    Propietario.persona_id,
                    Barrio.id,
                    Ambientes.id,
                    m.INMUEBLE_SUPERFICIETOTAL,
                    Disposicion.id,
                    Orientacion.id,
                    EstadoInmueble.id,
                    m.INMUEBLE_ANTIGUEDAD,
                    m.INMUEBLE_EXPESAS
    FROM gd_esquema.Maestra m
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_INMUEBLE TipoInmueble
                  ON TipoInmueble.id = m.INMUEBLE_TIPO_INMUEBLE
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PERSONA Persona
                  ON Persona.mail = m.PROPIETARIO_MAIL
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROPIETARIO Propietario
                  ON Propietario.persona_id = Persona.id
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO Barrio
                  ON Barrio.id = m.INMUEBLE_BARRIO
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AMBIENTES Ambientes
                  ON Ambientes.id = m.INMUEBLE_CANT_AMBIENTES
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DISPOSICION Disposicion
                  ON Disposicion.id = m.INMUEBLE_DISPOSICION
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ORIENTACION Orientacion
                  ON Orientacion.id = m.INMUEBLE_ORIENTACION
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_INMUEBLE EstadoInmueble
                  ON EstadoInmueble.id = m.INMUEBLE_ESTADO
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ANUNCIO
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ANUNCIO(fecha_publicacion, agente_id, tipo_operacion_id,
                                                                      inmueble_id, precio_publicado, tipo_moneda_id,
                                                                      tipo_periodo_id, estado_anuncio_id,
                                                                      fecha_finalizacion, costo_publicacion_anuncio)
    SELECT m.ANUNCIO_FECHA_PUBLICACION,
           Agente.persona_id,
           TipoOperacion.id,
           Inmueble.codigo,
           m.ANUNCIO_PRECIO_PUBLICADO,
           TipoMoneda.id,
           TipoPeriodo.id,
           EstadoAnuncio.id,
           m.ANUNCIO_FECHA_FINALIZACION,
           m.ANUNCIO_COSTO_ANUNCIO
    FROM gd_esquema.Maestra m
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PERSONA Persona
                  ON Persona.mail = m.AGENTE_MAIL
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AGENTE Agente
                  ON Agente.persona_id = Persona.id
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_OPERACION TipoOperacion
                  ON TipoOperacion.id = m.ANUNCIO_TIPO_OPERACION
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE Inmueble
                  ON Inmueble.codigo = m.INMUEBLE_CODIGO
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_MONEDA TipoMoneda
                  ON TipoMoneda.id = m.ANUNCIO_MONEDA
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_PERIODO TipoPeriodo
                  ON TipoPeriodo.id = m.ANUNCIO_TIPO_PERIODO
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ANUNCIO EstadoAnuncio
                  ON EstadoAnuncio.id = m.ANUNCIO_ESTADO
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PROVINCIA_X_LOCALIDAD
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA_X_LOCALIDAD(provincia_id, localidad_id)
    SELECT DISTINCT p.id, l.id
    FROM gd_esquema.Maestra m
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PROVINCIA p ON p.id = m.INMUEBLE_PROVINCIA
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.LOCALIDAD l ON l.id = m.INMUEBLE_LOCALIDAD
    ORDER BY 1
END
GO

CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_BARRIO_X_LOCALIDAD
AS
BEGIN
    INSERT INTO LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO_X_LOCALIDAD(barrio_id, localidad_id)
    SELECT DISTINCT b.id, l.id
    FROM gd_esquema.Maestra m
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.BARRIO b ON b.id = m.INMUEBLE_BARRIO
             JOIN LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.LOCALIDAD l ON l.id = m.INMUEBLE_LOCALIDAD
END
GO
-- Fin crear Procedimientos

-- Inicio Invocaciones de procedimientos
-- Migración de tablas paramétricas sin dependencias
EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PROVINCIA
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PERSONA
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_PERIODO
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_OPERACION
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ESTADO_ANUNCIO
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_MONEDA
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_MEDIO_PAGO
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ESTADO_ALQUILER
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ORIENTACION
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_DISPOSICION
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_TIPO_INMUEBLE
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_AMBIENTES
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ESTADO_INMUEBLE
GO

-- Migración de tablas paramétricas con dependencias
EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_LOCALIDAD
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_BARRIO
GO

-- Migración de tablas no paramétricas
EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PROPIETARIO
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_INQUILINO
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_COMPRADOR
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_SUCURSAL
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_AGENTE
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_INMUEBLE
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_ANUNCIO
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_PROVINCIA_X_LOCALIDAD
GO

EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_BARRIO_X_LOCALIDAD
GO
-- Fin Invocaciones de procedimientos
