USE [GD2C2023]
GO

-- Inicio Configurar reglas de nombre de objetos
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET CONCAT_NULL_YIELDS_NULL ON
GO
-- Fin Configurar reglas de nombre de objetos

-- Inicio DROP FKs
IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_DETALLE_IMPORTE_ALQ_ALQUILER_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DETALLE_IMPORTE_ALQ
    DROP CONSTRAINT FK_DETALLE_IMPORTE_ALQ_ALQUILER_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_PAGO_ALQUILER_MEDIO_PAGO_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER
    DROP CONSTRAINT FK_PAGO_ALQUILER_MEDIO_PAGO_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_PAGO_ALQUILER_ALQUILER_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER
    DROP CONSTRAINT FK_PAGO_ALQUILER_ALQUILER_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_PAGO_VENTA_TIPO_MONEDA_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
    DROP CONSTRAINT FK_PAGO_VENTA_TIPO_MONEDA_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_PAGO_VENTA_MEDIO_PAGO_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
    DROP CONSTRAINT FK_PAGO_VENTA_MEDIO_PAGO_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_PAGO_VENTA_VENTA_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
    DROP CONSTRAINT FK_PAGO_VENTA_VENTA_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_INMUEBLE_ORIENTACION_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    DROP CONSTRAINT FK_INMUEBLE_ORIENTACION_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_INMUEBLE_DISPOSICION_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    DROP CONSTRAINT FK_INMUEBLE_DISPOSICION_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_INMUEBLE_TIPO_INMUEBLE_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    DROP CONSTRAINT FK_INMUEBLE_TIPO_INMUEBLE_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_INMUEBLE_AMBIENTES_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    DROP CONSTRAINT FK_INMUEBLE_AMBIENTES_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_INMUEBLE_ESTADO_INMUEBLE_ID', 'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    DROP CONSTRAINT FK_INMUEBLE_ESTADO_INMUEBLE_ID
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_CARACTERISTICA_X_INMUEBLE_CODIGO_INMUEBLE',
             'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE
    DROP CONSTRAINT FK_CARACTERISTICA_X_INMUEBLE_CODIGO_INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.FK_CARACTERISTICA_X_INMUEBLE_CARACTERISTICA_INMUEBLE_ID',
             'F') IS NOT NULL
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE
    DROP CONSTRAINT FK_CARACTERISTICA_X_INMUEBLE_CARACTERISTICA_INMUEBLE_ID
GO

-- Fin DROP FKs

-- Inicio DROP tablas
IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DETALLE_IMPORTE_ALQ', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DETALLE_IMPORTE_ALQ
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ALQUILER', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ALQUILER
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MEDIO_PAGO', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MEDIO_PAGO
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_MONEDA', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_MONEDA
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DISPOSICION', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DISPOSICION
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ORIENTACION', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ORIENTACION
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_INMUEBLE', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AMBIENTES', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AMBIENTES
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_INMUEBLE', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_INMUEBLE', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_INMUEBLE
GO

IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE', 'U') IS NOT NULL
    DROP TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE
GO
-- Fin DROP tablas

-- Inicio DROP Funciones

-- Fin DROP Funciones

-- Inicio DROP Procedimientos
IF OBJECT_ID('LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_EJEMPLO_SP') IS NOT NULL
    DROP PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_EJEMPLO_SP
GO
-- Fin DROP Procedimientos

-- Inicio crear schema de la aplicación
IF EXISTS (SELECT SCHEMA_NAME
           FROM INFORMATION_SCHEMA.SCHEMATA
           WHERE SCHEMA_NAME = 'LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO')
    DROP SCHEMA LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO
GO

CREATE SCHEMA LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO
GO
-- Fin crear schema de la aplicación

-- Inicio crear tablas
CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DETALLE_IMPORTE_ALQ
(
    codigo             INT PRIMARY KEY,
    alquiler_id        INT            NOT NULL,
    nro_periodo_inicio NUMERIC(18, 2) NULL,
    nro_periodo_fin    NUMERIC(18, 2) NULL,
    precio             NUMERIC(18, 2) NULL,
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER
(
    codigo            INT PRIMARY KEY,
    alquiler_id       INT            NOT NULL,
    fecha_pago        DATETIME       NULL,
    nro_periodo_pago  NUMERIC(18, 0) NULL,
    descripcion       NVARCHAR(100)  NULL,
    fecha_inicio_pago DATETIME       NULL,
    fecha_fin_pago    DATETIME       NULL,
    importe           NUMERIC(18, 0) NULL,
    medio_pago_id     INT            NOT NULL,
    fecha_vencimiento DATETIME       NULL,
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
(
    codigo         INT PRIMARY KEY,
    importe        NUMERIC(18, 2) NULL,
    tipo_moneda_id INT            NOT NULL,
    cotizacion     NUMERIC(18, 2) NULL,
    medio_pago_id  INT            NOT NULL,
    venta_id       INT            NOT NULL,
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_ALQUILER
(
    id          INT PRIMARY KEY,
    descripcion NVARCHAR(100) NULL
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MEDIO_PAGO
(
    id          INT PRIMARY KEY,
    descripcion NVARCHAR(100) NULL
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_MONEDA
(
    id          INT PRIMARY KEY,
    descripcion NVARCHAR(100) NULL
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
(
    codigo             NUMERIC(18, 0) PRIMARY KEY,
    tipo_inmueble_id   INT,
    descripcion        NVARCHAR(100) NOT NULL,
    nombre             NVARCHAR(20),
    propietario_id     INT,
    barrio_id          INT,
    ambientes_id       INT,
    superficie_total   INT,
    disposicion_id     INT,
    orientacion_id     INT,
    estado_inmueble_id INT,
    antiguedad         INT,
    expensas           INT
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ORIENTACION
(
    id          INT IDENTITY (1,1) PRIMARY KEY,
    descripcion NVARCHAR(100)
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DISPOSICION
(
    id          INT IDENTITY (1,1) PRIMARY KEY,
    descripcion NVARCHAR(100)
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_INMUEBLE
(
    id          INT IDENTITY (1,1) PRIMARY KEY,
    descripcion NVARCHAR(100)
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AMBIENTES
(
    id          INT IDENTITY (1,1) PRIMARY KEY,
    descripcion NVARCHAR(100)
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_INMUEBLE
(
    id          INT IDENTITY (1,1) PRIMARY KEY,
    descripcion NVARCHAR(100)
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_INMUEBLE
(
    id          INT IDENTITY (1,1) PRIMARY KEY,
    descripcion NVARCHAR(20),
)
GO

CREATE TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE
(
    codigo_inmueble            NUMERIC(18, 0),
    caracteristica_inmueble_id INT,
    PRIMARY KEY (codigo_inmueble, caracteristica_inmueble_id),
)
GO
-- Fin crear tablas

-- Inicio crear FKs
/* TODO Descomentar al crear la tabla ALQUILER
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DETALLE_IMPORTE_ALQ
    ADD CONSTRAINT FK_DETALLE_IMPORTE_ALQ_ALQUILER_ID FOREIGN KEY (alquiler_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ALQUILER (codigo)
GO
*/

/* TODO Descomentar al crear la tabla ALQUILER
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER
    ADD CONSTRAINT FK_PAGO_ALQUILER_ALQUILER_ID FOREIGN KEY (alquiler_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ALQUILER (codigo)
GO
*/

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_ALQUILER
    ADD CONSTRAINT FK_PAGO_ALQUILER_MEDIO_PAGO_ID FOREIGN KEY (MEDIO_PAGO_ID) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MEDIO_PAGO (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
    ADD CONSTRAINT FK_PAGO_VENTA_TIPO_MONEDA_ID FOREIGN KEY (tipo_moneda_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_MONEDA (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
    ADD CONSTRAINT FK_PAGO_VENTA_MEDIO_PAGO_ID FOREIGN KEY (medio_pago_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MEDIO_PAGO (id)
GO

/* TODO Descomentar al crear la tabla VENTA
ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.PAGO_VENTA
    ADD CONSTRAINT FK_PAGO_VENTA_VENTA_ID FOREIGN KEY (venta_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.VENTA (codigo)
GO
*/

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    ADD CONSTRAINT FK_INMUEBLE_ORIENTACION_ID FOREIGN KEY (orientacion_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ORIENTACION (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    ADD CONSTRAINT FK_INMUEBLE_DISPOSICION_ID FOREIGN KEY (disposicion_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.DISPOSICION (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    ADD CONSTRAINT FK_INMUEBLE_TIPO_INMUEBLE_ID FOREIGN KEY (tipo_inmueble_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.TIPO_INMUEBLE (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    ADD CONSTRAINT FK_INMUEBLE_AMBIENTES_ID FOREIGN KEY (ambientes_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.AMBIENTES (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE
    ADD CONSTRAINT FK_INMUEBLE_ESTADO_INMUEBLE_ID FOREIGN KEY (estado_inmueble_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.ESTADO_INMUEBLE (id)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE
    ADD CONSTRAINT FK_CARACTERISTICA_X_INMUEBLE_CODIGO_INMUEBLE FOREIGN KEY (codigo_inmueble) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.INMUEBLE (codigo)
GO

ALTER TABLE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_X_INMUEBLE
    ADD CONSTRAINT FK_CARACTERISTICA_X_INMUEBLE_CARACTERISTICA_INMUEBLE_ID FOREIGN KEY (caracteristica_inmueble_id) REFERENCES LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.CARACTERISTICA_INMUEBLE (id)
GO
-- Fin crear FKs

-- Inicio crear Funciones

-- Fin crear Funciones

-- Inicio crear Procedimientos
CREATE PROCEDURE LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_EJEMPLO_SP
AS
BEGIN
    -- Cuerpo
    SELECT 1
END
GO
-- Fin crear Procedimientos

-- Inicio Invocaciones de procedimientos
EXEC LOS_HEREDEROS_DE_MONTIEL_Y_EL_DATO_PERSISTIDO.MIGRAR_EJEMPLO_SP
GO
-- Fin Invocaciones de procedimientos
